echo Creating CloudFormation Stack...
aws cloudformation create-stack --template-body file://EC2_Wazuh.json --stack-name WazuStack
aws cloudformation wait stack-create-complete --stack-name WazuStack
echo Stack Created!
echo Creating EC2 Instance...
echo This may take a few minutes...
#aws ec2 wait instance-status-ok --instance-name Ubuntu18Wazuh
